### ISSUE TITLE
来说两句

### ISSUE THREAD

**Issue by xiaomubiao** [nervouself/hexo-theme-shallow#1]
主题很简洁，只是
第一，你这logo 太辣眼睛
第二，Readmore按钮直接是橙色就好了，这样让主题颜色更亮一点
第三，图片一点就只变成图片了，据说有那个funcybox 可以考虑用一下
第四，引入代码，作为程序员你们都喜欢黑色背景的，但是我还是觉得素色一点的比较好，清淡 
总体不错，最近我打算弄个 日记本，找了一晚上主题觉得你的很好，简单，干净，大气

**Comment by nervouself** [comment]
第一，这logo是可以自己随便换的！！！
第二&第四，这个都可以改的！！！
第三，fancybox依赖第三方库，如果你需要，我这周可以帮你写一个纯净的

**Comment by nervouself** [comment]
可以私聊我，这几条我一起帮你改

**Comment by xiaomubiao** [comment]
真是好人啊，我就脸皮厚点吧
我给你发邮件吧，那个 个人资料的QQ 邮箱可以吧？

**Comment by nervouself** [comment]
可以，就那个邮箱
