### ISSUE TITLE
改完了以后 博客标题有下划线是什么问题？

### ISSUE THREAD

**Issue by xiaomubiao** [nervouself/hexo-theme-shallow#3]
.logo-title
  position: relative
  float: center
  font-size: 40px
  text-decoration: none
我把 Logo 部分都删除了，博客标题特效也删除了，但是博客标题出现了下划线，我设置了，为什么还会有这个问题，头疼，希望解答，谢谢了

**Comment by nervouself** [comment]
你要把a标签设置为没有下划线，还有大哥，以后这种问题就不要来提issue了。。。。你直接问我不行吗

**Comment by xiaomubiao** [comment]
不想加 QQ 话说你天天在啊，问题解决了，我随便把 left 改成center 了，貌似你没定义 center，改回来了就好了，谢谢了，我尽量不骚扰你
