### ISSUE TITLE
博客标题的下划线位置放的可能不对

### ISSUE THREAD

**Issue by xiaomubiao** [nervouself/hexo-theme-shallow#4]
原来是这个位置
.logo-title
  position:relative
  float: left
  font-size: 30px
  text-decoration: none
但是手机访问 博客标题的下划线就出来了，我测试了你的博客缩小窗口也有下划线，我把  text-decoration: none改到了.logo-wrap下面手机访问博客标题就没有下划线了。

**Comment by nervouself** [comment]
确实
